name: worker
author: Diego Rocha <diego.rocha.comp@gmail.com>
version: 0.3.6
homepage: https://github.com/Dreckr/Worker
description: Utility for easy concurrency with isolates
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  unittest: '>=0.5.0'
