name: worker
version: 0.6.0
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: Utility for easy concurrency with isolates
homepage: https://github.com/Dreckr/Worker
environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'
documentation: http://www.dartdocs.org/documentation/worker/0.5.0/index.html
dependencies:
  stack_trace: '>=0.9.0 <2.0.0'
dev_dependencies:
  test: '1.3.0'
