name: worker
version: 0.1.0
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: Utility for easy concurrency with isolates
environment:
  sdk: '>=0.5.0'
dev_dependencies:
  unittest: '>=0.5.0'

#dependencies:
#  js: any
#  unittest: any