name: worker
version: 0.2.1
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: Utility for easy concurrency with isolates
homepage: https://github.com/Dreckr/Worker
environment:
  sdk: '>=0.5.0'
dev_dependencies:
  unittest: '>=0.5.0'

#dependencies:
#  js: any
#  unittest: any