name: worker
version: 0.3.8
author: Diego Rocha <diego.rocha.comp@gmail.com>
description: Utility for easy concurrency with isolates
homepage: https://github.com/Dreckr/Worker
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  unittest: '>=0.5.0'
